{"name": "при создании нового заказа счётчик Выполнено за сегодня увеличивается", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Move target (160, 1231) is out of bounds of viewport dimensions (1280, 689)\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nMoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:479:5\nassertInViewPort@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2380:11\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1161:21\ndispatch/pendingEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2036:14\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2035:39\ndispatch/chainEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1946:27\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1948:7\nperformActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:491:23\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:144:31", "trace": "self = <tests.test_feed.TestFeed object at 0x0000021823233170>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"ae0e3366-c2e9-4026-b00b-f0eee14b4899\")>\nauthentication_user = None\n\n    @allure.sub_suite(\"Счетчики\")\n    @allure.title(\"при создании нового заказа счётчик Выполнено за сегодня увеличивается\")\n    def test_create_new_order_increment_day_counter(self, driver, authentication_user):\n    \n        feed = FeedPage(driver)\n        feed.get_url(Constants.URL_FEED)\n        feed.wait_element(FeedLocators.COUNTER_DAY)\n        number = int(feed.get_text_from_element(FeedLocators.COUNTER_DAY))\n    \n        feed.get_url(Constants.URL_HOME)\n>       feed.create_order(driver)\n\ntests\\test_feed.py:57: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\feed_page.py:58: in create_order\n    home.create_order()\npages\\home_page.py:29: in create_order\n    actions.drag_and_drop(drag_from, drag_to).click_and_hold().perform()\n.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py:94: in perform\n    self.w3c_actions.perform()\n.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py:96: in perform\n    self.driver.execute(Command.W3C_ACTIONS, enc)\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000002182327BD40>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"move target out of bounds\",\"message\":\"Move target (160, 1231) is out of b...ys.mjs:491:23\\\\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:144:31\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Move target (160, 1231) is out of bounds of viewport dimensions (1280, 689)\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       MoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:479:5\nE       assertInViewPort@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2380:11\nE       dispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1161:21\nE       dispatch/pendingEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2036:14\nE       dispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2035:39\nE       dispatch/chainEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1946:27\nE       dispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1948:7\nE       performActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:491:23\nE       receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:144:31\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: MoveTargetOutOfBoundsException"}, "steps": [{"name": "Переход к 'https://stellarburgers.nomoreparties.site/feed'", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/feed'"}], "start": 1729444614714, "stop": 1729444615017}, {"name": "ожидание элемента ('xpath', \"//p[text()='Выполнено за сегодня:']/following-sibling::p[contains(@class,'OrderFeed_number')]\")", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//p[text()='Выполнено за сегодня:']/following-sibling::p[contains(@class,'OrderFeed_number')]\")"}], "start": 1729444615019, "stop": 1729444617086}, {"name": "Получение текста элемента ('xpath', \"//p[text()='Выполнено за сегодня:']/following-sibling::p[contains(@class,'OrderFeed_number')]\")", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//p[text()='Выполнено за сегодня:']/following-sibling::p[contains(@class,'OrderFeed_number')]\")"}], "start": 1729444617087, "stop": 1729444617102}, {"name": "Переход к 'https://stellarburgers.nomoreparties.site/'", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/'"}], "start": 1729444617102, "stop": 1729444618062}, {"name": "Создание закака", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Move target (160, 1231) is out of bounds of viewport dimensions (1280, 689)\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nMoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:479:5\nassertInViewPort@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2380:11\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1161:21\ndispatch/pendingEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2036:14\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2035:39\ndispatch/chainEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1946:27\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1948:7\nperformActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:491:23\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:144:31\n\n", "trace": "  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\pages\\feed_page.py\", line 58, in create_order\n    home.create_order()\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\pages\\home_page.py\", line 29, in create_order\n    actions.drag_and_drop(drag_from, drag_to).click_and_hold().perform()\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py\", line 94, in perform\n    self.w3c_actions.perform()\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py\", line 96, in perform\n    self.driver.execute(Command.W3C_ACTIONS, enc)\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Создание заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Move target (160, 1231) is out of bounds of viewport dimensions (1280, 689)\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nMoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:479:5\nassertInViewPort@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2380:11\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1161:21\ndispatch/pendingEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2036:14\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2035:39\ndispatch/chainEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1946:27\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1948:7\nperformActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:491:23\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:144:31\n\n", "trace": "  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\pages\\home_page.py\", line 29, in create_order\n    actions.drag_and_drop(drag_from, drag_to).click_and_hold().perform()\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py\", line 94, in perform\n    self.w3c_actions.perform()\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py\", line 96, in perform\n    self.driver.execute(Command.W3C_ACTIONS, enc)\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\yandex\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Переход к 'https://stellarburgers.nomoreparties.site/'", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/'"}], "start": 1729444618062, "stop": 1729444618379}, {"name": "ожидание элементов ('xpath', '//div[contains(@class,\"BurgerIngredients_ingredients\")]/ul[1]/a')", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', '//div[contains(@class,\"BurgerIngredients_ingredients\")]/ul[1]/a')"}], "start": 1729444618379, "stop": 1729444618932}, {"name": "ожидание элемента ('xpath', \"//section[contains(@class,'BurgerConstructor_basket')]\")", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//section[contains(@class,'BurgerConstructor_basket')]\")"}], "start": 1729444618932, "stop": 1729444618952}, {"name": "ожидание элементов ('xpath', '//div[contains(@class,\"BurgerIngredients_ingredients\")]/ul[3]/a')", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', '//div[contains(@class,\"BurgerIngredients_ingredients\")]/ul[3]/a')"}], "start": 1729444619526, "stop": 1729444619546}, {"name": "ожидание элемента ('xpath', \"//section[contains(@class,'BurgerConstructor_basket')]\")", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//section[contains(@class,'BurgerConstructor_basket')]\")"}], "start": 1729444619546, "stop": 1729444619565}], "start": 1729444618062, "stop": 1729444619571}], "parameters": [{"name": "driver", "value": "<selenium.webdriver.firefox.webdriver.WebDriver (session=\"ae0e3366-c2e9-4026-b00b-f0eee14b4899\")>"}], "start": 1729444618062, "stop": 1729444619572}], "parameters": [{"name": "driver", "value": "'Firefox'"}], "start": 1729444614713, "stop": 1729444619573, "uuid": "ed70b80a-5c11-4270-b451-b8ce4af3e0b5", "historyId": "96d3bfbc82beaafd598aca29ab6effa9", "testCaseId": "89b29a2d59bd896c24abcbc9630c525b", "fullName": "tests.test_feed.TestFeed#test_create_new_order_increment_day_counter", "labels": [{"name": "subSuite", "value": "Счетчики"}, {"name": "feature", "value": "Лента заказов"}, {"name": "suite", "value": "Лента заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "KITCHEN"}, {"name": "thread", "value": "2020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed"}]}